[package]
name = "czi-ssh"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
test-fake-child = []

[[bin]]
name = "czi-ssh-pty-fake-child"
path = "src/bin/czi-ssh-pty-fake-child.rs"
required-features = ["test-fake-child"]

[[test]]
name = "embedded_pty"
path = "tests/embedded_pty.rs"
required-features = ["test-fake-child"]

[dependencies]
czi-core = { path = "../czi-core" }

[target.'cfg(target_os = "macos")'.dependencies]
czi-ssh-darwin = { path = "../czi-ssh-darwin" }
